### ISSUE TITLE
ubuntu 下无法编译通过

### ISSUE THREAD

**Issue by makefriend8** [rts-cn/books#2]
Ubuntu 20.04 

错误提示如下
/books/fsbook-case-study$ make
cp -R images out/
pandoc --toc -o out/fsbook-case-study-0.html \
--variable book="FreeSWITCH案例大全" \
--variable title="FreeSWITCH案例大全" \
--template cover.html \
meta.md 01/index.md 01/prefix.md 01/leg-timeout.md 01/acl.md chapter-moyan.md chapter-alwaysrun.md section-wsl.md chapter2.md section-503.md chapter3.md section-from-to.md section-sip-trunk.md chapterX.md chapter-client.md Android.md postface.md
pandoc -s --toc --variable documentclass="report" \
--variable book="FreeSWITCH案例大全" \
--template cover.tex \
--number-sections \
--pdf-engine=xelatex \
--include-before=header.tex \
--include-in-header=ncover.tex \
--include-before-body=out/preface.tex \
--include-after-body=cover-back.tex \
-o out/FreeSWITCH案例大全-标准版-0.pdf \
meta.md 01/index.md 01/prefix.md 01/leg-timeout.md 01/acl.md chapter-moyan.md chapter-alwaysrun.md section-wsl.md chapter2.md section-503.md chapter3.md section-from-to.md section-sip-trunk.md chapterX.md chapter-client.md Android.md postface.md
Error producing PDF.
! LaTeX Error: File `zhspacing.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.46 ^^M

make: *** [Makefile:122：pdf] 错误 43

**Comment by seven1240** [comment]
推荐使用Docker编译：https://github.com/rts-cn/books/commit/1ae66daee29fbb4615012aec463064e7d5315331

你那个应该是少了zhspacing包，试试以下命令是否能成功。

```
tlmgr install zhspacing
```

也可以尝试注释掉`cover.tex`中的以下行：

```
\usepackage{zhspacing}
```
